export const styles = {
  pageWrapper: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    bg: '$accent100' as const,
    padding: '$6' as const,
  },
  card: {
    width: '$full' as const,
    maxWidth: 480,
    bg: '$white' as const,
    borderRadius: '$2xl' as const,
    padding: '$8' as const,
    shadowColor: '$shadowColor' as const,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
    alignItems: 'center' as const,
    borderWidth: 1,
    borderColor: '$borderColor' as const,
  },
  iconWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    bg: '$primary100' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: '$4' as const,
  },
  badge: {
    bg: '$success100' as const,
    borderRadius: '$full' as const,
    paddingHorizontal: '$3' as const,
    paddingVertical: '$1' as const,
    marginBottom: '$2' as const,
  },
  badgeText: {
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
    color: '$success700' as const,
  },
  appName: {
    fontSize: '$2xl' as const,
    fontWeight: '$bold' as const,
    textAlign: 'center' as const,
    color: '$textPrimary' as const,
    marginBottom: '$1' as const,
  },
  description: {
    fontSize: '$sm' as const,
    textAlign: 'center' as const,
    color: '$textSecondary' as const,
    marginBottom: '$4' as const,
    maxWidth: 340,
  },
  downloadButton: {
    variant: 'solid' as const,
    size: 'lg' as const,
    bg: '$primary500' as const,
    width: '$full' as const,
    maxWidth: 200,
  },
  warningBox: {
    bg: '$error100' as const,
    borderRadius: '$lg' as const,
    padding: '$3' as const,
    marginTop: '$4' as const,
    width: '$full' as const,
    borderWidth: 1,
    borderColor: '$error200' as const,
  },
  warningText: {
    fontSize: '$xs' as const,
    color: '$error600' as const,
    textAlign: 'center' as const,
  },
} as const;
