export const dashboardHeaderStyles = {
  container: {
    space: 'xs' as const,
    mb: 0 as const,
  },
  filterBoxWrapper: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderColor' as const,
    borderRadius: '$xl' as const,
    width: '$full' as const,
    mb: '$2' as const,
    p: 8,
    gap: 8,
    $md: {
      height: 52,
      p: 8,
      gap: 8,
    },
    // Shadow matching design
    shadowColor: '$shadowColor' as const,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  filterIcon: {
    color: '$primary500' as const,
    size: 13,
    ml: 8,
  },
  filterButtonOverride: {
    mt: 0,
    p: 0,
    borderWidth: 0,
    bg: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
    width: 'auto',
    flex: 1,
  },
  filterInputOverride: {
    height: 36,
    borderRadius: '$md' as const,
    bg: '$white' as const,
    borderColor: '$borderColor' as const,
  },
  tabsContainer: {
    bg: '$accent200' as const,
    borderRadius: 16,
    p: 3,
    height: 40,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    alignSelf: 'flex-start' as const,
    borderWidth: 0,
    mb: 0 as const,
    width: '$full' as const,
    $md: {
      width: 672,
    },
  },
  tabButton: (isActive: boolean) => ({
    flex: 1 as const,
    bg: isActive ? '$white' : 'transparent',
    borderRadius: 13,
    px: '$4',
    height: 30,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    elevation: isActive ? 1 : 0,
    shadowColor: isActive ? '$shadowColor' : 'transparent',
    shadowOffset: isActive ? { width: 0, height: 1 } : { width: 0, height: 0 },
    shadowOpacity: isActive ? 0.1 : 0,
    shadowRadius: isActive ? 1 : 0,
  }),
  tabText: (isActive: boolean) => ({
    fontSize: 14,
    fontWeight: isActive ? ('$semibold' as any) : ('$normal' as any),
    color: isActive ? '$textForeground' : '$textMutedForeground',
  }),
} as const;
