export const performanceActivityStyles = {
  card: {
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderColor' as const,
    borderRadius: 20,
    p: '$6' as const,
    width: '$full' as const,
    shadowColor: '$shadowColor' as const,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    _hover: {
      shadowColor: '$textMutedForeground' as const,
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
  },
  header: {
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    mb: '$6' as const,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '$textForeground' as const,
  },
  cardDescription: {
    fontSize: 13,
    color: '$textMutedForeground' as const,
  },
  periodTabs: {
    bg: '$accent200' as const,
    borderRadius: 14,
    p: 2,
    height: 28,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    borderWidth: 0,
    width: 140,
  },
  tabButton: (isActive: boolean) => ({
    flex: 1 as const,
    bg: isActive ? '$primary500' : 'transparent',
    borderRadius: 12,
    height: 24,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    elevation: 0,
    shadowOpacity: 0,
  }),
  tabText: (isActive: boolean) => ({
    fontSize: 12,
    fontWeight: isActive ? ('$semibold' as any) : ('$normal' as any),
    color: isActive ? '$white' : '$textMutedForeground',
  }),
  metricGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    marginHorizontal: -8,
    rowGap: 16,
    marginTop: '$2' as const,
  },
  metricCardWrapper: {
    width: '100%' as const,
    paddingHorizontal: 8,
    $sm: {
      width: '50%' as const,
    },
    $md: {
      width: '25%' as const,
    },
  },
  metricCard: (borderToken: string) => ({
    borderWidth: 1,
    borderColor: borderToken,
    borderRadius: 12,
    p: '$4' as const,
    bg: '$white' as const,
    justifyContent: 'space-between' as const,
    minHeight: 128,
  }),
  metricIcon: (bgToken: string) => ({
    p: '$1.5' as const,
    borderRadius: 8,
    bg: bgToken,
  }),
  metricLabel: {
    fontSize: 13,
    fontWeight: '$medium' as const,
    color: '$textForeground' as const,
    flexShrink: 1,
  },
  metricValue: (colorToken: string) => ({
    fontSize: 24,
    fontWeight: '$bold' as const,
    color: colorToken,
  }),
  metricDescription: {
    fontSize: 11,
    color: '$textMutedForeground' as const,
  },
} as const;
