export const schemaFormStyles = {
  container: { space: 'lg', w: '$full' },
  section: {
    w: '$full',
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: '$lg',
    p: '$4',
  },
  sectionHeader: { space: 'sm', alignItems: 'center', mb: '$4' },
  sectionIconWrap: {
    w: '$8',
    h: '$8',
    borderRadius: '$md',
    bg: '$primary50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: '$md',
    fontWeight: '$semibold',
    color: '$textDark900',
  },
  rowSpacing: { mb: '$3' },
  rowElevated: { zIndex: 1 },
  fieldWrap: { space: 'xs', flex: 1 },
  label: { fontSize: '$sm', fontWeight: '$medium', color: '$textDark800' },
  requiredMark: { color: '$red600' },
  errorText: { fontSize: '$xs', color: '$red600' },
  inputField: { flex: 1 },
  submitButton: {
    size: 'lg',
    w: '$full',
    variant: 'solid',
    action: 'primary',
    mt: '$2',
  },
  submitButtonText: { color: '$white', fontWeight: '$semibold' },
} as const;
