export const mySessionsStyles = {
  page: {
    flex: 1 as const,
    bg: '$white' as const,
  },
  topHeaderBar: {
    width: '$full' as const,
    bg: '$white' as const,
    borderBottomWidth: 1 as const,
    borderBottomColor: '$inputBorder' as const,
  },
  headerContainer: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$4' as const,
    '$md-px': '$8' as const,
  },
  headerTitleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  backPressable: {
    borderRadius: '$md' as const,
  },
  backIconBox: {
    p: '$2' as const,
    bg: 'transparent' as const,
    borderRadius: '$md' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  backIconBoxHover: {
    bg: '$primary100' as const,
  },
  title: {
    color: '$textDark900' as const,
    fontSize: '$xl' as const,
    fontWeight: '$bold' as const,
  },
  contentArea: {
    flex: 1 as const,
    width: '$full' as const,
    bg: '$accent100' as const,
  },
  container: {
    width: '$full' as const,
    px: '$6' as const,
    py: '$6' as const,
    '$md-px': '$8' as const,
    '$md-py': '$8' as const,
  },
  content: {
    space: 'md' as const,
    alignItems: 'stretch' as const,
    width: '$full' as const,
  },
  subtitle: {
    color: '$textDark600' as const,
    fontSize: '$md' as const,
    fontWeight: '$normal' as const,
    mb: '$6' as const,
  },
  tabsContainer: {
    flexDirection: 'row' as const,
    bg: '$backgroundLightGray100' as const,
    p: '$1' as const,
    borderRadius: '$full' as const,
    alignSelf: 'flex-start' as const,
    mb: '$6' as const,
  },
  tabItem: {
    px: '$6' as const,
    py: '$2' as const,
    borderRadius: '$full' as const,
  },
  tabItemActive: {
    bg: '$white' as const,
    shadowColor: '$shadowColor' as const,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1 as const,
  },
  tabItemInactive: {
    bg: 'transparent' as const,
  },
  tabText: {
    fontSize: '$sm' as const,
    fontWeight: '$medium' as const,
  },
  tabTextActive: {
    color: '$textDark900' as const,
    fontWeight: '$semibold' as const,
  },
  tabTextInactive: {
    color: '$textDark600' as const,
    fontWeight: '$medium' as const,
  },
  cardsGrid: {
    flexDirection: 'column' as const,
    '$md-flexDirection': 'row' as const,
    flexWrap: 'wrap' as const,
    gap: '$4' as const,
    width: '$full' as const,
  },
  cardBox: {
    width: '$full' as const,
    '$md-width': 'calc(50% - 8px)' as const,
    bg: '$white' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    borderRadius: '$xl' as const,
    p: '$5' as const,
  },
  cardHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    space: 'sm' as const,
    mb: '$1' as const,
  },
  cardTitle: {
    color: '$textDark900' as const,
    fontSize: '$md' as const,
    fontWeight: '$bold' as const,
    flex: 1 as const,
    lineHeight: '$md' as const,
  },
  cardSubtitle: {
    color: '$textDark600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
    mt: '$1' as const,
    mb: '$3' as const,
  },
  statusBadgeScheduled: {
    bg: '$blue50' as const,
    borderColor: '$blue200' as const,
    borderWidth: 1 as const,
    borderRadius: '$full' as const,
    px: '$2.5' as const,
    py: '$0.5' as const,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: '$1' as const,
  },
  statusBadgeAttended: {
    bg: '$success50' as const,
    borderColor: '$success300' as const,
    borderWidth: 1 as const,
    borderRadius: '$full' as const,
    px: '$2.5' as const,
    py: '$0.5' as const,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: '$1' as const,
  },
  statusBadgeMissed: {
    bg: '$error50' as const,
    borderColor: '$error200' as const,
    borderWidth: 1 as const,
    borderRadius: '$full' as const,
    px: '$2.5' as const,
    py: '$0.5' as const,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: '$1' as const,
  },
  statusTextScheduled: {
    color: '$blue600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
  },
  statusTextAttended: {
    color: '$success600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
  },
  statusTextMissed: {
    color: '$error600' as const,
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
  },
  metaRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    space: 'xs' as const,
    mb: '$2' as const,
  },
  metaText: {
    color: '$textDark600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
  },
  locationRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    space: 'xs' as const,
    mb: '$2' as const,
  },
  locationText: {
    color: '$textDark600' as const,
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
  },
  tagsRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: '$2' as const,
    mt: '$3' as const,
  },
  tagChip: {
    px: '$3' as const,
    py: '$1' as const,
    borderRadius: '$md' as const,
    borderWidth: 1 as const,
    borderColor: '$inputBorder' as const,
    bg: '$white' as const,
  },
  tagText: {
    color: '$textDark900' as const,
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
  },
  emptyStateContainer: {
    width: '$full' as const,
    py: '$10' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  emptyStateText: {
    color: '$textDark600' as const,
    fontSize: '$md' as const,
  },
} as const;
